name: Dart CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code using V1 of the standard checkout Action
    - uses: actions/checkout@v2
    # Use the standard Java Action to setup Java
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Use the community Action to install Flutter
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.13+hotfix.6'
        channel: 'beta'
    - run: flutter pub get
    - run: flutter test
